baseurl = "https://stronglytyped.me/"
languageCode = "en-gb"
title = "strongly typed"
theme = "hyde-x"
MetaDataFormat = "toml"
paginate = 10
DisqusShortname = "saxonmatt"

[params]
    theme = "theme-base-08"
    layoutReverse = true
    highlight = "monokai"
    tagline = "husband, father, nerd, strong person, code monkey, coach and teller of stories"
    gravatarHash = "da7bcb58b36bd8c0e29fe2be0eb1c8ff"
    github = "https://github.com/mattdrivendev"
    twitter = "https://twitter.com/MattDrivenDev"
    youtube = "https://www.youtube.com/channel/UCA5cXOM8EPfs7uI82XrFq-A"
    instagram = "https://www.instagram.com/strongly.typed/"
    rss = true
    googleAnalytics = "UA-26103642-1"

[taxonomies]
    category = "categories"
    tags = "tags"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[author]
    name = "Matt Ball"
    twitter = "MattDrivenDev"
    github = "MattDrivenDev"
    linkedin = "matt-ball-98120940"